TampereHacklab/mulysa

users/admin.py
users/signals.py
users/tests.py

when new servicesubscription is created without reference number generate one automatically for it.
fixes #138

Generate servicesubscription referencenumber. fixes #138

---

utils/dataimport.py

Strip leading zeroes from ref.num. on Holvi-importer.
Fix holvi-importer ignoring first parsed line.

Holvi-importer fixes

---

emails/templates/admin/send-email.html
emails/templates/emails/email_detail.html
emails/templates/mail_content_and_post.html
emails/templates/mail_content_and_post.txt
emails/tests.py

Better test case and use different templates for rendering the txt and html versions of the email content

Fix email encoding, fixes #289

---

api/tests.py
users/signals.py
users/templates/mail/door_access_denied.txt

These templates require a full rewrite anyway with #172 so just add the information at the end for now.

Subscription information in accessdenied email, fixes #291

---

www/templates/www/user.html
www/templates/www/users.html

* hide admin actions from userdetails page, these can be accessed from users listing
* remove create new user from users list, this link is way too easy to click on mobile and all user creation should anyway go trough the regular flow

Cleanup extra staff actions in user views

---

www/templates/www/users.html
www/urls.py
www/views.py

this is needed as the updateusers does not always see what happened.
basically clicking on the button runs businesslogic.updateuser for that user (which it should have done automatically)
Until the automation gets fixed for good lets leave the button here.

reintroduce the updateuser functionality for admins

---

Pipfile.lock

> py 1.9.0 has known security vulnerabilities.
> A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality. See CVE-2020-29651.

Update all dependencies.

---

Pipfile
Pipfile.lock
drfx/settings.py

Update to Django 3.2 which is a LTS version. 3.1 support is ending in December.
3.x extended support ends April 2024.
https://www.djangoproject.com/download/
DEFAULT_AUTO_FIELD see: https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys

Django 3.2 and update to all other packages also

---

api/tests.py
users/signals.py

Let send_mail fail silently if sending the "your door access was denied" fails
and a test for it

Door api smtp error

---

nginx/nginx.conf

ok, so this fixes the email reset link to be https
BUT it does not seem to fix the "token already used" problem with clicking the link in gmail...

nginx forwarded-proto: pass the forwarded-proto header that traefik set

---

README.md

This section got left in in my previous PR by accident. 
One thing I'm unsure of is what Python version should be listed as a prerequisite.

docs: remove old prerequisite list

---

.github/workflows/codeql-analysis.yml

The v1 actions have been deprecated: https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

chore: bump codeQL workflows

---

users/tests.py
www/static/www/graphs.js

chartjs does not seem to have a way to automatically "group and sum" dataset.
Implement grouping and summing with javascript from the daily data.
(and few more test as I initially thought there was an error on the python side of things :)
This removes the "weekly" grouping (dates in js are a pain)

Fix transaction graph grouping by summing the data

---

www/templates/www/user.html

Some users have been confused by the wording here, assuming that it means that custom invoices should be used for repeated payments, when their purpose is to allow paying multiple months of service in one invoice. This should hopefully clarify the wording a bit.
The Finnish version of this page is already more explicit about the purpose of custom invoices:
> Jos haluat maksaa palvelun useaan kertaan yhdellä tilisiirrolla, voit tehdä vapaamuotoisen laskun.

Clarify English wording of custom invoices on user.html.

---

www/static/www/graphs.js

Kinda ugly, but this shows better graph when using the "group by year".
It should really fetch the data again and use a longer timespan as grouping by year could easily show 10 years of data.

Always fetch the whole previous year and all of this year so far

---

drfx/settings.py
users/admin.py
users/filters.py
users/management/commands/delete_marked_users.py
users/signals.py
users/templates/mail/account_deactivated_and_marked_for_deletion.txt
users/tests/test_user_deletion.py

Add few admin tools to help with marking the users
Add script (not crontabbed yet) for deleting marked users
Add tests for user deletion

User cleanup

---

users/admin.py

Django admin panel crashed error with null birthday, when tried to add new custom user. Adding all fields that are present on mylsa add user field it is now possible to add custom user trough django admin panel.

Make it possible to create new user from django admin panel

---

Pipfile.lock
www/static/www/bootstrap4/jquery-3.5.1.min.js.map

This updates Nordigen library to 1.4.0 which is important as it includes update to the api endpoint urls. The old urls will stop working after a while.

Update dependecies and bootstrap

---

.github/workflows/tox.yml

save few cpu cycles by ending the old ci run if new commits are pushed in while the old checks are running
source: 
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow

if new changes are pushed kill old ci runs

---

users/models/bank_transaction.py

User relation can be null but form validation doesn't allow for blank values. Allow blank values to make it possible to comment transactions without users.
closes #513

fix: allow user in bank transaction to be blank in forms

---

utils/dataimport.py
www/forms.py
www/views.py

The import is written to just get old tampere members imported for the first time. There is no real need for that format anymore and the code was not that great anyway. Just remove it completely.
Also makes the holvi import be the intially selected option as it is the most used import. 
And marks TITO import as deprecated (it only works for nordea Tito files and nordigen is much better for nordea anyway)

Remove members import. Fixes #118

---

api/views.py

This removes code duplication for now and makes it easier to work with future refactors.
4bfbed3
- Moves logic from 3 separate functions into one
- Adds logging to phone access
I would recommend to review this by opening the abstraction function and one of the original functions side by side and comparing, then repeating this for the rest of the original functions.
-----
7feb3cd Reorders a function in the file.

Combine NFC, MXID, and phone number door access logic

---

tox.ini
users/locale/fi/LC_MESSAGES/django.po

also remove pager from the diff output
there is still a "problem" with this. tox runs the makemessages to see the diff and that changes your working directory which is not perfect..
and as different versions of makemessages and po editors seem to do linechanges differently we will have some noise in translations

CI fix exit-code for makemessage diff, 

---

users/tests/test_payments.py
utils/businesslogic.py
utils/locale/fi/LC_MESSAGES/django.po
www/templates/www/user.html

Custom invoice payment logic has been carried out with its own function which will only move selected service paid_to date froward.
This PR change Custominvoice to use standard payment logic
Fixes issue of child subscriptions not get paid: #270

Mulysa custom invoice paid by transaction

---

users/locale/fi/LC_MESSAGES/django.po
www/locale/fi/LC_MESSAGES/django.po
www/templates/www/user.html
www/templates/www/users.html

I added the Matrix ID to the Users List and to the User detail page, in order to make admin searching easier, and to make the matrix ID more visible to the member.
I did not make any changes to the pre-existing style.  I just matched it, using single quotes where single quotes were already being used.
Translations should not be necessary for "Matrix ID"

Add matrix ID to www pages

---

www/views.py

Newly added feature to send emails to users via usersetting page allowed email sends only to other staff members. This PR fixes that so that staff member can send email to anyuser. It allso hides send email field from regular member as it is not practical to send email back to self.

Allow admin to send emails to non staff user
