TampereHacklab/mulysa

- drfx/settings.py
- setup.cfg
- users/apps.py
- users/models.py
- utils/businesslogic.py
- www/apps.py
- www/urls.py
- www/views.py
```
$ tox -e flake8
flake8 installed: entrypoints==0.3,flake8==3.7.7,flake8-isort==2.7.0,flake8-quotes==2.0.1,isort==4.3.21,mccabe==0.6.1,pycodestyle==2.5.0,pyflakes==2.1.1,testfixtures==6.10.0
flake8 run-test-pre: PYTHONHASHSEED='2079978637'
flake8 run-test: commands[0] | flake8
_____________________________________________________________________________ summary _____________________________________________________________________________
flake8: commands succeeded
congratulations :)
```
> Fix flake8

- Readme.md
- users/fixtures/memberservices.json
> fixtures for memberservice

- Pipfile.lock
> Update to django 3.0.1 and update others also

- Pipfile.lock
- setup.cfg
https://www.djangoproject.com/weblog/2020/feb/03/security-releases/
> Update django to 3.0.3

- Pipfile
- Pipfile.lock
- drfx/settings.py
- drfx/urls.py
- utils/emailbackend.py
initial working version of password reset
email backend with logging
add admin even when debug is off
> Password reset

- drfx/settings.py
- www/context_processors.py
- www/templates/www/register.html
move urls to settings
use context_processor and fix the links in translations
> Fix links in registration

- users/models.py
- www/templates/www/base.html
- www/templates/www/index.html
from https://github.com/TampereHacklab/mulysa/commit/6b60705a296d5034ea015431c9f627a6b1cd88ca#commitcomment-37435294
> New frontpage text

- drfx/settings.py
- users/signals.py
- users/templates/mail/application_received.html
- users/templates/mail/application_rejected.html
- users/templates/mail/email_base.html
- users/templates/mail/new_application.html
- users/templates/mail/welcome_and_next_steps.html
- utils/businesslogic.py
- www/templates/www/applications.html
- www/templates/www/thanks.html
- www/views.py
* two stage welcome emails
* after application is created: thank you, we will check your application
* after application is approve / rejected: welcome / rejected email
* notification email to admins of new application
Fixes: #86
> Better email triggers

- www/forms.py
- www/templates/www/register.html
better error message for services if none selected
> registration form form error messages

- Pipfile
- Pipfile.lock
- docker-compose.yml
- drfx/settings.py
- emails/README.md
- emails/forms.py
- emails/jobs/process_queue.py
- emails/jobs/retry_deferred.py
- ofelia.ini
- www/templates/registration/login.html
* use django-mailer to get a email queue
* use django-cron to have cron tasks as code
* add ofelia to run the cron tasks
> Emailqueue and cron

- dooractivator/test_sms.py
- setup.cfg
- utils/businesslogic.py
blackening the code does quite a lot of changes. decided to add this as a pr to the feature branch.
> docstrings, logger and blackened few files

- users/models.py
> Make matrix-id field optional

- Pipfile
- Pipfile.lock
- utils/dataimport.py
- utils/holvitoolbox.py
- www/forms.py
- www/views.py
Importer and parser for holvi.
> Holvi importer

- README.md
- api/tests.py
- api/views.py
Reports custom RFC-compliant response codes in access API to various conditions depending what didn't found or failed, more thoughts on #166. Also document responses on Readme.
> Better API response codes

- api/serializers.py
> Report nickname in succesfull API call.

- api/views.py
- users/models.py
and supress log message in has_door_access for user.
> Faster and better queryset for accesslisting api

- users/jobs/notify_expiring_services.py
- users/templates/mail/service_subscription_about_to_expire.txt
- users/tests.py
- utils/businesslogic.py
* new job that runs daily
* searches for all subscriptions that are about to expire and queues email to notify users about the oncoming expiration
> Subscription notification feature, fixes #222

- api/tests.py
- api/views.py
- users/signals.py
- users/templates/mail/door_access_denied.txt
sends email to user that explains that they should check their status by logging into mulysa.
> new signal door_access_denied fixes #230

- README.md
Seems to be somekind of load order problem.
just updated readme to have correct commands to start :)
> add --skip-checks to readme for starting, fixes 152

- Pipfile.lock
update all the packages.
will rebase #252 after this is merged
> pipenv update to get latest packages

- users/models.py
> Show cost min/max more sanely if either one is N/A

- www/forms.py
- www/views.py
allow user to define the price to be paid per unit during creation of custom invoice
> Custominvoice amount, fixes #232 

- .github/workflows/codeql-analysis.yml
https://securitylab.github.com/tools/codeql
https://github.com/github/codeql-action
> set up codeql-analysis

- drfx/settings.py
- www/templates/www/users.html
I think this is something we could use :)
> Show last login in users list

- api/views.py
one more place for user to see why they didn't get in.
#275 is getting more important
> add userlog entry for denied/accepted door access

- .github/workflows/latest-changes.yml
- CHANGELOG.md
Automatic CHANGELOG.md from PR:s
> Adding https://github.com/tiangolo/latest-changes

- Pipfile
- Pipfile.lock
See https://github.com/z4r/python-coveralls/issues/74
> Switch coveralls package, fixes #96

- CHANGELOG.md
- Pipfile
- Pipfile.lock
- www/templates/www/base.html
- www/templates/www/changelog.html
- www/tests.py
- www/urls.py
- www/views.py
> Show changelog, fixes #301

- www/static/www/mulysa.js
just a quick and dirty js highlight for the labels
> highlight required fields in forms, fixes #277

- Pipfile.lock
https://docs.djangoproject.com/en/3.1/releases/3.1.5/
> Update django to 3.1.5

- www/templates/www/index.html
> Better way to check if membershipapplication is still pending

- Pipfile.lock
and all the other requirements also
> Update django to 3.2.6

- README.md
> Finish OIDC setup documentation

- www/decorators.py
- www/views.py
add new decorator to dry the "this is me or staff" checks in views.
and using redirect_to_login looks like it should be safe
> Sanitize url redirect

- Dockerfile
- docker-compose.yml
- entrypoint.sh
- nginx/Dockerfile
Speed up re-building Docker containers.
> Speed up Docker container builds

- api/tests.py
while doing a demo on how to write tests and check test coverage I used this project as an example and what do you know we have one new test and bit better coverage :)
yeah, its not perfect but better than nothing
> add basic test for oauth2validator method

- README.md
- drfx/settings.py
BUT this wont work with localhost as it does not have ssl..
Add this to your `settings_local.py`
```
SESSION_COOKIE_NAME = '__NotReallyHost-sessionid'
LANGUAGE_COOKIE_NAME = '__NotReallyHost-language'
CSRF_COOKIE_NAME = '__NotReallyHost-csrf'
```
> More secure cookies, fixes #370

- Pipfile.lock
Update django to 4.1.2 and all the other dependencies too
> Pipenv update for 2022/11, updates django to 4.1.2

- Pipfile
- Pipfile.lock
What pyup did here: #399 but manually
> Update django 4.1.3

- users/admin.py
makes it easier to check transactions
> add few fields to banktransaction view for easier checking

- drfx/settings.py
- nginx/nginx.conf
is given by nginx and trust it
> Default to configuration where X-Forwarded-Proto

- nginx/nginx.conf
> fix missing semicolon

- www/static/www/graphs.js
- www/templates/www/graphs.html
So that the first month is complete
Change header to be "rolling 12 months"
> Start graph always from first day of the month

- www/templates/www/custominvoice.html
- www/templates/www/user.html
Some changes were suggested to the custom invoice texts
https://matrix.to/#/!RsUTIzdZIWSNaRSEIe:hacklab.fi/$JsA4SHorwwmjhX-fVUPcVu9wjfH11HHZiiMawKsTv3c?via=hacklab.fi&via=irc.snt.utwente.nl&via=matrix.org
Also tried to make it clearer that one should not use the custom invoices all the time
> Small changes to custominvoice texts suggested on tampere channels

- README.md
> remove pyup from readme

- Pipfile.lock
Update to django 4.2.8
https://docs.djangoproject.com/en/5.0/releases/4.2.8/
> Django 4.2.8

- Pipfile.lock
supercedes: https://github.com/TampereHacklab/mulysa/pull/504 and https://github.com/TampereHacklab/mulysa/pull/502
> Django 4.2.17 and other depencies update

- www/templates/www/base.html
> fix: show hamburger navbar on larger breakpoint

- users/tests/test_user_deletion.py
bad formatting introduced in https://github.com/TampereHacklab/mulysa/commit/28993ff356edcb4a7079fd28df05bc041e37d4f5
> chore: format badly formatted file

- .github/workflows/latest-changes.yml
Master was protected and that broke the latest changes ci jobs. 
first try to fix that.
> Try to fix latest changes

- www/templates/www/base.html
> Add link to admin site for superusers' nav bar

- README.md
This can be done as a one liner, so why not?
> docs: simplify homebrew installation command

- users/locale/fi/LC_MESSAGES/django.po
- www/locale/fi/LC_MESSAGES/django.po
- www/templates/www/user.html
> UI: show overdue days to member

- www/locale/fi/LC_MESSAGES/django.po
- www/views.py
Fixes missing printf-style format character in named string Fixes issue #573
> Fix for string formatting

- www/locale/fi/LC_MESSAGES/django.po
- www/templates/www/base.html
Logout by GET method is no longer supported.
Replaced with POST link button
.CSS changes would be needed to have colors to match
It seems that pipenv sync --dev, also broke make messages check.
> Fix of logout button
